apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: webapp-test
  namespace: {DEVOPSNS}
spec:
  inputs:
    resources:
      - name: webapp-gitsrc
        type: git
      - name: webapp-image
        type: image
    params:
      - name: testScript
        description: The path to the bash file for testing
  steps:
  - name: modify-app-deploy-yaml
    image: registry.access.redhat.com/ubi8/ubi:latest
    workingDir: /workspace/webapp-gitsrc
    command: ["/bin/bash"]
    args:
      - -c
      - |
        export APPNAME=webapp
        export PORT=8000
        export DEVNS=lightblue-dev
        bash /workspace/webapp-gitsrc/test/$(inputs.params.testScript)
