#!/bin/bash
### Setting configuration defaults
#
# appname will be used as the prefix for all application resources
#
appname="template"
#
# appversion is added to appname to indicate version
#
appversion="1.0"
#
# apptype is the application type - useful to select the stage for build - such as nodejs/java/dotnet etc
#
apptype="nodejs"
#
# namespaces
#
devopsns="tekton"
devns="app-dev"
qans="app-qa"
prodns="app-prod"
#
# port number the application listen to
#
port="8000"
#
# build - keep to true
#
build="true"
#
# the following deploy statements determine which level do you wanted to deploy
#
deploydev="true"
deployqa="false"
