apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webapp-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - name: webapp-listener
    bindings:
     - name: webapp-push-binding
       ref: webapp-push-binding
    template:
      name: webapp-triggertemplate
