apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webapp-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - binding:
      name: webapp-pullrequest-binding
    template:
      name: webapp-triggertemplate
  - binding:
      name: webapp-push-binding
    template:
      name: webapp-triggertemplate
