apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: webapp-deployment
  labels:
    appgroup: webapp
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: webapp-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: webapp
      template:
        metadata:
          name: pod-webapp
          labels:
            app: webapp
        spec:
          containers:
            - name: webapp
              image: __IMAGE__
              imagePullPolicy: Always
              livenessProbe:
                tcpSocket:
                  port: 8000
                initialDelaySeconds: 20
                periodSeconds: 60
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: webapp-service
  labels:
    appgroup: webapp
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: webapp-service
      labels:
        app: webapp
    spec:
      type: NodePort
      selector:
        app: webapp
      ports:
       - protocol: TCP
         port: 8000
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: webapp-route
  labels:
    appgroup: webapp
spec:
  template:
    apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: webapp
    spec:
      port:
        targetPort: 8000
      to:
        kind: Service
        name: webapp-service
        weight: 100
