apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: webapp-placementrule
  namespace: devops
  labels:
    appgroup: webapp
spec:
  clusterLabels:
    matchLabels:
      name: cpeir033
  clusterReplicas:  1
