apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: webapp-subscription-qa
  namespace: devops
  labels:
    appgroup: webapp
spec:
  channel: devops/webapp-channel
  packageFilter:
    labelSelector:
      matchLabels:
        appgroup: webapp
  placement:
    placementRef:
      kind: PlacementRule
      name: webapp-placementrule
  overrides:
   - clusterName: "/"
     clusterOverrides:
      - path: "metadata.namespace"
        value: app-qa
