apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: webapp-pipeline
spec:
  resources:
    - name: webapp-gitsrc
      type: git
    - name: webapp-image
      type: image
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: "k8s"
    - name: deploy-dev
      description: deploy to dev
      default: "true"
    - name: deploy-qa
      description: deploy to qa
      default: "false"
  tasks:
  - name: scan-task
    resources:
      inputs:
        - name: webapp-gitsrc
          resource: webapp-gitsrc
    params:
      - name: SONAR_HOST_URL
        value: ""
      - name: SONAR_PROJECT_KEY
        value: ""
    taskRef:
      name: webapp-check
  - name: build-task
    resources:
      inputs:
        - name: webapp-gitsrc
          resource: webapp-gitsrc
        - name: webapp-image
          resource: webapp-image
    runAfter:
      - scan-task
    taskRef:
      name: webapp-build
  - name: deploy-dev
    #when: the when operator will be available in v0.16
    #  - input: $(params.deploy-dev)
    #    operator: in
    #    values: ["true"]
    #  - input: $(tasks.test-task.results.ok)
    #    operator: in
    #    values: ["yes"]
    resources:
      inputs:
        - name: webapp-gitsrc
          resource: webapp-gitsrc
        - name: webapp-image
          resource: webapp-image
    params:
      - name: pathToYamlFile
        value: "k8s"
      - name: devns
        value: "lightblue-dev"
    runAfter:
      - build-task
    taskRef:
      name: webapp-deploy-dev
  - name: test
    #when:
    #  - input: $(params.deploy-dev)
    #    operator: in
    #    values: ["true"]
    #  - input: $(tasks.deploy-dev.results.ok)
    #    operator: in
    #    values: ["yes"]
    resources:
      inputs:
        - name: webapp-gitsrc
          resource: webapp-gitsrc
        - name: webapp-image
          resource: webapp-image
    params:
      - name: testScript
        value: "dev-test.sh"
    runAfter:
      - deploy-dev
    taskRef:
      name: webapp-test
  - name: deploy-qa
    #when:
    #  - input: $(params.deploy-qa)
    #    operator: in
    #    values: ["true"]
    #  - input: $(tasks.test-task.results.ok)
    #    operator: in
    #    values: ["yes"]
    resources:
      inputs:
        - name: webapp-gitsrc
          resource: webapp-gitsrc
        - name: webapp-image
          resource: webapp-image
    params:
      - name: pathToYamlFile
        value: "k8s"
      - name: devns
        value: "lightblue-dev"
      - name: devopsns
        value: "{DEVOPSNS}"
      - name: qans
        value: "lightblue-qa"
    runAfter:
      - test
    taskRef:
      name: webapp-deploy-qa
